<?php

declare(strict_types=1);

namespace Brick\Schema\Interfaces;

use Brick\Schema\SchemaTypeList;
use Brick\Schema\DataType\Date;
use Brick\Schema\DataType\DateTime;
use Brick\Schema\DataType\Text;
use Brick\Schema\DataType\Number;
use Brick\Schema\DataType\Boolean;

/**
 * schema:CreativeWork
 *
 * @property-read SchemaTypeList<Date|DateTime>                                        $dateModified         The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.
 * @property-read SchemaTypeList<MediaObject>                                          $associatedMedia      A media object that encodes this CreativeWork. This property is a synonym for encoding.
 * @property-read SchemaTypeList<Organization>                                         $publisherImprint     The publishing division which published the comic.
 * @property-read SchemaTypeList<DefinedTerm|Text>                                     $pattern              A pattern that something has, for example 'polka dot', 'striped', 'Canadian flag'. Values are typically expressed as text, although links to controlled value schemes are also supported.
 * @property-read SchemaTypeList<AudioObject|MusicRecording|Clip>                      $audio                An embedded audio object.
 * @property-read SchemaTypeList<Event>                                                $recordedAt           The Event where the CreativeWork was recorded. The CreativeWork may capture all or part of the event.
 * @property-read SchemaTypeList<CreativeWork>                                         $hasPart              Indicates an item or CreativeWork that is part of this item, or CreativeWork (in some sense).
 * @property-read SchemaTypeList<Text>                                                 $awards               Awards won by or for this item.
 * @property-read SchemaTypeList<MediaObject>                                          $encoding             A media object that encodes this CreativeWork. This property is a synonym for associatedMedia.
 * @property-read SchemaTypeList<CreativeWork>                                         $workTranslation      A work that is a translation of the content of this work. E.g. 西遊記 has an English workTranslation “Journey to the West”, a German workTranslation “Monkeys Pilgerfahrt” and a Vietnamese  translation Tây du ký bình khảo.
 * @property-read SchemaTypeList<PublicationEvent>                                     $releasedEvent        The place and time the release was issued, expressed as a PublicationEvent.
 * @property-read SchemaTypeList<CreativeWork>                                         $workExample          Example/instance/realization/derivation of the concept of this creative work. E.g. the paperback edition, first edition, or e-book.
 * @property-read SchemaTypeList<Place>                                                $spatial              The "spatial" property can be used in cases when more specific properties
 * @property-read SchemaTypeList<ItemList>                                             $accessModeSufficient A list of single or combined accessModes that are sufficient to understand all the intellectual content of a resource. Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessModeSufficient-vocabulary).
 * @property-read SchemaTypeList<Text>                                                 $award                An award won by or for this item.
 * @property-read SchemaTypeList<Review>                                               $review               A review of the item.
 * @property-read SchemaTypeList<Claim>                                                $interpretedAsClaim   Used to indicate a specific claim contained, implied, translated or refined from the content of a [[MediaObject]] or other [[CreativeWork]]. The interpreting party can be indicated using [[claimInterpreter]].
 * @property-read SchemaTypeList<Organization|Person>                                  $publisher            The publisher of the creative work.
 * @property-read SchemaTypeList<CreativeWork>                                         $exampleOfWork        A creative work that this work is an example/instance/realization/derivation of.
 * @property-read SchemaTypeList<URL|Text>                                             $genre                Genre of the creative work, broadcast channel or group.
 * @property-read SchemaTypeList<CreativeWork>                                         $translationOfWork    The work that this work has been translated from. E.g. 物种起源 is a translationOf “On the Origin of Species”.
 * @property-read SchemaTypeList<Text>                                                 $headline             Headline of the article.
 * @property-read SchemaTypeList<CreativeWork|URL>                                     $acquireLicensePage   Indicates a page documenting how licenses can be purchased or otherwise acquired, for the current item.
 * @property-read SchemaTypeList<Text|DefinedTerm>                                     $assesses             The item being described is intended to assess the competency or learning outcome defined by the referenced term.
 * @property-read SchemaTypeList<Text|DefinedTerm>                                     $creativeWorkStatus   The status of a creative work in terms of its stage in a lifecycle. Example terms include Incomplete, Draft, Published, Obsolete. Some organizations define a set of terms for the stages of their publication lifecycle.
 * @property-read SchemaTypeList<URL|CreativeWork>                                     $sdLicense            A license document that applies to this structured data, typically indicated by URL.
 * @property-read SchemaTypeList<Text|DefinedTerm>                                     $educationalUse       The purpose of a work in the context of education; for example, 'assignment', 'group work'.
 * @property-read SchemaTypeList<Country>                                              $countryOfOrigin      The country of origin of something, including products as well as creative  works such as movie and TV content.
 * @property-read SchemaTypeList<Rating|Text>                                          $contentRating        Official rating of a piece of content—for example, 'MPAA PG-13'.
 * @property-read SchemaTypeList<Place>                                                $locationCreated      The location where the CreativeWork was created, which may not be the same as the location depicted in the CreativeWork.
 * @property-read SchemaTypeList<Organization|Person>                                  $creator              The creator/author of this CreativeWork. This is the same as the Author property for CreativeWork.
 * @property-read SchemaTypeList<Text>                                                 $accessibilitySummary A human-readable summary of specific accessibility features or deficiencies, consistent with the other accessibility metadata but expressing subtleties such as "short descriptions are present but long descriptions will be needed for non-visual users" or "short descriptions are present and no long descriptions are needed".
 * @property-read SchemaTypeList<Integer>                                              $commentCount         The number of comments this CreativeWork (e.g. Article, Question or Answer) has received. This is most applicable to works published in Web sites with commenting system; additional comments may exist elsewhere.
 * @property-read SchemaTypeList<Number>                                               $copyrightYear        The year during which the claimed copyright for the CreativeWork was first asserted.
 * @property-read SchemaTypeList<URL|CreativeWork|Product>                             $isBasedOnUrl         A resource that was used in the creation of this resource. This term can be repeated for multiple sources. For example, http://example.com/great-multiplication-intro.html.
 * @property-read SchemaTypeList<URL|CreativeWork>                                     $license              A license document that applies to this content, typically indicated by URL.
 * @property-read SchemaTypeList<URL|CreativeWork>                                     $usageInfo            The schema.org [[usageInfo]] property indicates further information about a [[CreativeWork]]. This property is applicable both to works that are freely available and to those that require payment or other transactions. It can reference additional information, e.g. community expectations on preferred linking and citation conventions, as well as purchasing details. For something that can be commercially licensed, usageInfo can provide detailed, resource-specific information about licensing options.
 * @property-read SchemaTypeList<PublicationEvent>                                     $publication          A publication event associated with the item.
 * @property-read SchemaTypeList<Duration>                                             $timeRequired         Approximate or typical time it usually takes to work with or through the content of this work for the typical or target audience.
 * @property-read SchemaTypeList<Text>                                                 $interactivityType    The predominant mode of learning supported by the learning resource. Acceptable values are 'active', 'expositive', or 'mixed'.
 * @property-read SchemaTypeList<URL|CreativeWork>                                     $publishingPrinciples The publishingPrinciples property indicates (typically via [[URL]]) a document describing the editorial principles of an [[Organization]] (or individual, e.g. a [[Person]] writing a blog) that relate to their activities as a publisher, e.g. ethics or diversity policies. When applied to a [[CreativeWork]] (e.g. [[NewsArticle]]) the principles are those of the party primarily responsible for the creation of the [[CreativeWork]].
 * @property-read SchemaTypeList<Organization|Person>                                  $contributor          A secondary contributor to the CreativeWork or Event.
 * @property-read SchemaTypeList<Text|CreativeWork>                                    $citation             A citation or reference to another creative work, such as another publication, web page, scholarly article, etc.
 * @property-read SchemaTypeList<Text>                                                 $conditionsOfAccess   Conditions that affect the availability of, or method(s) of access to, an item. Typically used for real world items such as an [[ArchiveComponent]] held by an [[ArchiveOrganization]]. This property is not suitable for use as a general Web access control mechanism. It is expressed only in natural language.\n\nFor example "Available by appointment from the Reading Room" or "Accessible only from logged-in accounts ". 
 * @property-read SchemaTypeList<DefinedTerm|Text>                                     $learningResourceType The predominant type or kind characterizing the learning resource. For example, 'presentation', 'handout'.
 * @property-read SchemaTypeList<URL|Text|CorrectionComment>                           $correction           Indicates a correction to a [[CreativeWork]], either via a [[CorrectionComment]], textually or in another document.
 * @property-read SchemaTypeList<Person|Organization>                                  $author               The author of this content or rating. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably.
 * @property-read SchemaTypeList<Review>                                               $reviews              Review of the item.
 * @property-read SchemaTypeList<URL|CreativeWork>                                     $isPartOf             Indicates an item or CreativeWork that this item, or CreativeWork (in some sense), is part of.
 * @property-read SchemaTypeList<Person|Organization>                                  $producer             The person or organization who produced the work (e.g. music album, movie, TV/radio series etc.).
 * @property-read SchemaTypeList<ImageObject>                                          $thumbnail            Thumbnail image for an image or video.
 * @property-read SchemaTypeList<Text>                                                 $accessMode           The human sensory perceptual system or cognitive faculty through which a person may process or perceive information. Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessMode-vocabulary).
 * @property-read SchemaTypeList<Text|URL>                                             $editEIDR             An [EIDR](https://eidr.org/) (Entertainment Identifier Registry) [[identifier]] representing a specific edit / edition for a work of film or television.
 * @property-read SchemaTypeList<DateTime|Text|URL>                                    $temporalCoverage     The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes, either as a DateTime or as a textual string indicating a time period in [ISO 8601 time interval format](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals). In
 * @property-read SchemaTypeList<Organization|Person>                                  $copyrightHolder      The party holding the legal copyright to the CreativeWork.
 * @property-read SchemaTypeList<AlignmentObject>                                      $educationalAlignment An alignment to an established educational framework.
 * @property-read SchemaTypeList<Grant>                                                $funding              A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].
 * @property-read SchemaTypeList<Text|URL|Product>                                     $material             A material that something is made from, e.g. leather, wool, cotton, paper.
 * @property-read SchemaTypeList<Text>                                                 $alternativeHeadline  A secondary title of the CreativeWork.
 * @property-read SchemaTypeList<Number|Text>                                          $version              The version of the CreativeWork embodied by a specified resource.
 * @property-read SchemaTypeList<Boolean>                                              $isFamilyFriendly     Indicates whether this content is family friendly.
 * @property-read SchemaTypeList<Text|QuantitativeValue>                               $materialExtent       The quantity of the materials being described or an expression of the physical space they occupy.
 * @property-read SchemaTypeList<URL>                                                  $discussionUrl        A link to the page containing the comments of the CreativeWork.
 * @property-read SchemaTypeList<Text|QuantitativeValue|DefinedTerm|SizeSpecification> $size                 A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured [[SizeSpecification]]; in other cases, the [[width]], [[height]], [[depth]] and [[weight]] properties may be more applicable. 
 * @property-read SchemaTypeList<Organization|Person>                                  $maintainer           A maintainer of a [[Dataset]], software package ([[SoftwareApplication]]), or other [[Project]]. A maintainer is a [[Person]] or [[Organization]] that manages contributions to, and/or publication of, some (typically complex) artifact. It is common for distributions of software and data to be based on "upstream" sources. When [[maintainer]] is applied to a specific version of something e.g. a particular version or packaging of a [[Dataset]], it is always  possible that the upstream source has a different maintainer. The [[isBasedOn]] property can be used to indicate such relationships between datasets to make the different maintenance roles clear. Similarly in the case of software, a package may have dedicated maintainers working on integration into software distributions such as Ubuntu, as well as upstream maintainers of the underlying work.
 * @property-read SchemaTypeList<Text>                                                 $copyrightNotice      Text of a notice appropriate for describing the copyright aspects of this Creative Work, ideally indicating the owner of the copyright for the Work.
 * @property-read SchemaTypeList<Comment>                                              $comment              Comments, typically from users.
 * @property-read SchemaTypeList<Demand|Offer>                                         $offers               An offer to provide this item—for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
 * @property-read SchemaTypeList<Text>                                                 $text                 The textual content of this CreativeWork.
 * @property-read SchemaTypeList<Text|URL>                                             $fileFormat           Media type, typically MIME format (see [IANA site](http://www.iana.org/assignments/media-types/media-types.xhtml)) of the content, e.g. application/zip of a SoftwareApplication binary. In cases where a CreativeWork has several media type representations, 'encoding' can be used to indicate each MediaObject alongside particular fileFormat information. Unregistered or niche file formats can be indicated instead via the most appropriate URL, e.g. defining Web page or a Wikipedia entry.
 * @property-read SchemaTypeList<MediaObject>                                          $encodings            A media object that encodes this CreativeWork.
 * @property-read SchemaTypeList<Thing>                                                $about                The subject matter of the content.
 * @property-read SchemaTypeList<Audience>                                             $audience             An intended audience, i.e. a group for whom something was created.
 * @property-read SchemaTypeList<Text|URL|DefinedTerm>                                 $keywords             Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.
 * @property-read SchemaTypeList<Place>                                                $spatialCoverage      The spatialCoverage of a CreativeWork indicates the place(s) which are the focus of the content. It is a subproperty of
 * @property-read SchemaTypeList<Organization|Person>                                  $sponsor              A person or organization that supports a thing through a pledge, promise, or financial contribution. E.g. a sponsor of a Medical Study or a corporate sponsor of an event.
 * @property-read SchemaTypeList<Text>                                                 $accessibilityAPI     Indicates that the resource is compatible with the referenced accessibility API. Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityAPI-vocabulary).
 * @property-read SchemaTypeList<Organization|Person>                                  $sdPublisher          Indicates the party responsible for generating and publishing the current structured data markup, typically in cases where the structured data is derived automatically from existing published content but published on a different site. For example, student projects and open data initiatives often re-publish existing content with more explicitly structured metadata. The
 * @property-read SchemaTypeList<Place>                                                $contentLocation      The location depicted or described in the content. For example, the location in a photograph or painting.
 * @property-read SchemaTypeList<InteractionCounter>                                   $interactionStatistic The number of interactions for the CreativeWork using the WebSite or SoftwareApplication. The most specific child type of InteractionCounter should be used.
 * @property-read SchemaTypeList<Text|URL>                                             $encodingFormat       Media type typically expressed using a MIME format (see [IANA site](http://www.iana.org/assignments/media-types/media-types.xhtml) and [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)), e.g. application/zip for a SoftwareApplication binary, audio/mpeg for .mp3 etc.
 * @property-read SchemaTypeList<URL|WebPage>                                          $archivedAt           Indicates a page or other link involved in archival of a [[CreativeWork]]. In the case of [[MediaReview]], the items in a [[MediaReviewItem]] may often become inaccessible, but be archived by archival, journalistic, activist, or law enforcement organizations. In such cases, the referenced page may not directly publish the content.
 * @property-read SchemaTypeList<Thing>                                                $mainEntity           Indicates the primary entity described in some page or other CreativeWork.
 * @property-read SchemaTypeList<Date|DateTime>                                        $datePublished        Date of first publication or broadcast. For example the date a [[CreativeWork]] was broadcast or a [[Certification]] was issued.
 * @property-read SchemaTypeList<Boolean>                                              $isAccessibleForFree  A flag to signal that the item, event, or place is accessible for free.
 * @property-read SchemaTypeList<Date|DateTime>                                        $dateCreated          The date on which the CreativeWork was created or the item was added to a DataFeed.
 * @property-read SchemaTypeList<Text|DefinedTerm>                                     $teaches              The item being described is intended to help a person learn the competency or learning outcome defined by the referenced term.
 * @property-read SchemaTypeList<URL>                                                  $thumbnailUrl         A thumbnail image relevant to the Thing.
 * @property-read SchemaTypeList<Person>                                               $accountablePerson    Specifies the Person that is legally accountable for the CreativeWork.
 * @property-read SchemaTypeList<Text>                                                 $typicalAgeRange      The typical expected age range, e.g. '7-9', '11-'.
 * @property-read SchemaTypeList<Date>                                                 $sdDatePublished      Indicates the date on which the current structured data was generated / published. Typically used alongside [[sdPublisher]].
 * @property-read SchemaTypeList<Organization|Person>                                  $funder               A person or organization that supports (sponsors) something through some kind of financial contribution.
 * @property-read SchemaTypeList<Date|DateTime>                                        $expires              Date the content expires and is no longer useful or available. For example a [[VideoObject]] or [[NewsArticle]] whose availability or relevance is time-limited, a [[ClaimReview]] fact check whose publisher wants to indicate that it may no longer be relevant (or helpful to highlight) after some date, or a [[Certification]] the validity has expired.
 * @property-read SchemaTypeList<AggregateRating>                                      $aggregateRating      The overall rating, based on a collection of reviews or ratings, of the item.
 * @property-read SchemaTypeList<DateTime|Text>                                        $temporal             The "temporal" property can be used in cases where more specific properties
 * @property-read SchemaTypeList<Text>                                                 $accessibilityControl Identifies input methods that are sufficient to fully control the described resource. Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityControl-vocabulary).
 * @property-read SchemaTypeList<Text>                                                 $accessibilityFeature Content features of the resource, such as accessible media, alternatives and supported enhancements for accessibility. Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityFeature-vocabulary).
 * @property-read SchemaTypeList<Text|Language>                                        $inLanguage           The language of the content or performance or used in an action. Please use one of the language codes from the [IETF BCP 47 standard](http://tools.ietf.org/html/bcp47). See also [[availableLanguage]].
 * @property-read SchemaTypeList<Person|Organization>                                  $provider             The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
 * @property-read SchemaTypeList<Text>                                                 $abstract             An abstract is a short description that summarizes a [[CreativeWork]].
 * @property-read SchemaTypeList<IPTCDigitalSourceEnumeration>                         $digitalSourceType    Indicates an IPTCDigitalSourceEnumeration code indicating the nature of the digital source(s) for some [[CreativeWork]].
 * @property-read SchemaTypeList<Integer|Text>                                         $position             The position of an item in a series or sequence of items.
 * @property-read SchemaTypeList<Thing>                                                $mentions             Indicates that the CreativeWork contains a reference to, but is not necessarily about a concept.
 * @property-read SchemaTypeList<Organization>                                         $sourceOrganization   The Organization on whose behalf the creator was working.
 * @property-read SchemaTypeList<VideoObject|Clip>                                     $video                An embedded video object.
 * @property-read SchemaTypeList<Person>                                               $editor               Specifies the Person who edited the CreativeWork.
 * @property-read SchemaTypeList<Text>                                                 $creditText           Text that can be used to credit person(s) and/or organization(s) associated with a published Creative Work.
 * @property-read SchemaTypeList<Text|URL>                                             $schemaVersion        Indicates (by URL or string) a particular version of a schema used in some CreativeWork. This property was created primarily to
 * @property-read SchemaTypeList<Person|Organization>                                  $translator           Organization or person who adapts a creative work to different languages, regional differences and technical requirements of a target market, or that translates during some event.
 * @property-read SchemaTypeList<Text>                                                 $accessibilityHazard  A characteristic of the described resource that is physiologically dangerous to some users. Related to WCAG 2.0 guideline 2.3. Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityHazard-vocabulary).
 * @property-read SchemaTypeList<DateTime>                                             $contentReferenceTime The specific time described by a creative work, for works (e.g. articles, video objects etc.) that emphasise a particular moment within an Event.
 * @property-read SchemaTypeList<Text|URL|DefinedTerm>                                 $educationalLevel     The level in terms of progression through an educational or training context. Examples of educational levels include 'beginner', 'intermediate' or 'advanced', and formal sets of level indicators.
 * @property-read SchemaTypeList<Person>                                               $character            Fictional person connected with a creative work.
 * @property-read SchemaTypeList<Product|URL|CreativeWork>                             $isBasedOn            A resource from which this work is derived or from which it is a modification or adaptation.
 */
interface CreativeWork extends Thing
{
}
