<?php

declare(strict_types=1);

namespace Brick\Schema\Interfaces;

use Brick\Schema\SchemaTypeList;
use Brick\Schema\DataType\Text;
use Brick\Schema\DataType\Date;
use Brick\Schema\DataType\DateTime;
use Brick\Schema\DataType\Time;
use Brick\Schema\DataType\Number;
use Brick\Schema\DataType\Boolean;

/**
 * schema:Offer
 *
 * @property-read SchemaTypeList<GeoShape|Text|Place>                                             $eligibleRegion            The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is valid.\n\nSee also [[ineligibleRegion]].
 * @property-read SchemaTypeList<Text>                                                            $gtin14                    The GTIN-14 code of the product, or the product to which the offer refers. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.
 * @property-read SchemaTypeList<Date|DateTime|Time>                                              $availabilityStarts        The beginning of the availability of the product or service included in the offer.
 * @property-read SchemaTypeList<Text>                                                            $priceCurrency             The currency of the price, or a price component when attached to [[PriceSpecification]] and its subtypes.\n\nUse standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR".
 * @property-read SchemaTypeList<Review>                                                          $review                    A review of the item.
 * @property-read SchemaTypeList<WarrantyPromise>                                                 $warranty                  The warranty promise(s) included in the offer.
 * @property-read SchemaTypeList<QuantitativeValue>                                               $eligibleQuantity          The interval and unit of measurement of ordering quantities for which the offer or price specification is valid. This allows e.g. specifying that a certain freight charge is valid only for a certain quantity.
 * @property-read SchemaTypeList<Person|Organization>                                             $offeredBy                 A pointer to the organization or person making the offer.
 * @property-read SchemaTypeList<QuantitativeValue>                                               $hasMeasurement            A measurement of an item, For example, the inseam of pants, the wheel size of a bicycle, the gauge of a screw, or the carbon footprint measured for certification by an authority. Usually an exact measurement, but can also be a range of measurements for adjustable products, for example belts and ski bindings.
 * @property-read SchemaTypeList<QuantitativeValue>                                               $deliveryLeadTime          The typical delay between the receipt of the order and the goods either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup.
 * @property-read SchemaTypeList<QuantitativeValue>                                               $advanceBookingRequirement The amount of time that is required between accepting the offer and the actual usage of the resource or service.
 * @property-read SchemaTypeList<Place>                                                           $availableAtOrFrom         The place(s) from which the offer can be obtained (e.g. store locations).
 * @property-read SchemaTypeList<OfferItemCondition>                                              $itemCondition             A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.
 * @property-read SchemaTypeList<Text|Number>                                                     $price                     The offer price of a product, or of a price component when attached to PriceSpecification and its subtypes.\n\nUsage guidelines:\n\n* Use the [[priceCurrency]] property (with standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR") instead of including [ambiguous symbols](http://en.wikipedia.org/wiki/Dollar_sign#Currencies_that_use_the_dollar_or_peso_sign) such as '$' in the value.\n* Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator.\n* Note that both [RDFa](http://www.w3.org/TR/xhtml-rdfa-primer/#using-the-content-attribute) and Microdata syntax allow the use of a "content=" attribute for publishing simple machine-readable values alongside more human-friendly formatting.\n* Use values from 0123456789 (Unicode 'DIGIT ZERO' (U+0030) to 'DIGIT NINE' (U+0039)) rather than superficially similar Unicode symbols.
 * @property-read SchemaTypeList<Date>                                                            $priceValidUntil           The date after which the price is no longer available.
 * @property-read SchemaTypeList<Text>                                                            $gtin12                    The GTIN-12 code of the product, or the product to which the offer refers. The GTIN-12 is the 12-digit GS1 Identification Key composed of a U.P.C. Company Prefix, Item Reference, and Check Digit used to identify trade items. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.
 * @property-read SchemaTypeList<PropertyValue>                                                   $additionalProperty        A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\n\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.
 * @property-read SchemaTypeList<Review>                                                          $reviews                   Review of the item.
 * @property-read SchemaTypeList<PriceSpecification>                                              $eligibleTransactionVolume The transaction volume, in a monetary unit, for which the offer or price specification is valid, e.g. for indicating a minimal purchasing volume, to express free shipping above a certain order volume, or to limit the acceptance of credit cards to purchases to a certain minimal amount.
 * @property-read SchemaTypeList<Text|Place|AdministrativeArea|GeoShape>                          $areaServed                The geographic area where a service or offered item is provided.
 * @property-read SchemaTypeList<Text>                                                            $serialNumber              The serial number or any alphanumeric identifier of a particular product. When attached to an offer, it is a shortcut for the serial number of the product included in the offer.
 * @property-read SchemaTypeList<MerchantReturnPolicy>                                            $hasMerchantReturnPolicy   Specifies a MerchantReturnPolicy that may be applicable.
 * @property-read SchemaTypeList<Boolean>                                                         $isFamilyFriendly          Indicates whether this content is family friendly.
 * @property-read SchemaTypeList<TypeAndQuantityNode>                                             $includesObject            This links to a node or nodes indicating the exact quantity of the products included in  an [[Offer]] or [[ProductCollection]].
 * @property-read SchemaTypeList<Time|Date|DateTime>                                              $availabilityEnds          The end of the availability of the product or service included in the offer.
 * @property-read SchemaTypeList<OfferShippingDetails>                                            $shippingDetails           Indicates information about the shipping policies and options associated with an [[Offer]].
 * @property-read SchemaTypeList<Date|DateTime>                                                   $validFrom                 The date when the item becomes valid.
 * @property-read SchemaTypeList<CreativeWork|Trip|MenuItem|Event|Product|AggregateOffer|Service> $itemOffered               An item being offered (or demanded). The transactional nature of the offer or demand is documented using [[businessFunction]], e.g. sell, lease etc. While several common expected types are listed explicitly in this definition, others can be used. Using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
 * @property-read SchemaTypeList<AdultOrientedEnumeration>                                        $hasAdultConsideration     Used to tag an item to be intended or suitable for consumption or use by adults only.
 * @property-read SchemaTypeList<Text>                                                            $mobileUrl                 The [[mobileUrl]] property is provided for specific situations in which data consumers need to determine whether one of several provided URLs is a dedicated 'mobile site'.
 * @property-read SchemaTypeList<Text>                                                            $mpn                       The Manufacturer Part Number (MPN) of the product, or the product to which the offer refers.
 * @property-read SchemaTypeList<LoanOrCredit|PaymentMethod>                                      $acceptedPaymentMethod     The payment method(s) accepted by seller for this offer.
 * @property-read SchemaTypeList<PriceSpecification>                                              $priceSpecification        One or more detailed price specifications, indicating the unit price and delivery or payment charges.
 * @property-read SchemaTypeList<Text>                                                            $checkoutPageURLTemplate   A URL template (RFC 6570) for a checkout page for an offer. This approach allows merchants to specify a URL for online checkout of the offered product, by interpolating parameters such as the logged in user ID, product ID, quantity, discount code etc. Parameter naming and standardization are not specified here.
 * @property-read SchemaTypeList<Text|URL|CategoryCode|PhysicalActivityCategory|Thing>            $category                  A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
 * @property-read SchemaTypeList<Date|DateTime>                                                   $validThrough              The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.
 * @property-read SchemaTypeList<Text|URL>                                                        $gtin                      A Global Trade Item Number ([GTIN](https://www.gs1.org/standards/id-keys/gtin)). GTINs identify trade items, including products and services, using numeric identification codes.
 * @property-read SchemaTypeList<Text>                                                            $gtin13                    The GTIN-13 code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceding zero. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.
 * @property-read SchemaTypeList<Person|Organization>                                             $seller                    An entity which offers (sells / leases / lends / loans) the services / goods.  A seller may also be a provider.
 * @property-read SchemaTypeList<Text|Place|GeoShape>                                             $ineligibleRegion          The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is not valid, e.g. a region where the transaction is not allowed.\n\nSee also [[eligibleRegion]].
 * @property-read SchemaTypeList<AggregateRating>                                                 $aggregateRating           The overall rating, based on a collection of reviews or ratings, of the item.
 * @property-read SchemaTypeList<Text>                                                            $sku                       The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.
 * @property-read SchemaTypeList<BusinessFunction>                                                $businessFunction          The business function (e.g. sell, lease, repair, dispose) of the offer or component of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.
 * @property-read SchemaTypeList<DeliveryMethod>                                                  $availableDeliveryMethod   The delivery method(s) available for this offer.
 * @property-read SchemaTypeList<QuantitativeValue>                                               $eligibleDuration          The duration for which the given offer is valid.
 * @property-read SchemaTypeList<Text>                                                            $gtin8                     The GTIN-8 code of the product, or the product to which the offer refers. This code is also known as EAN/UCC-8 or 8-digit EAN. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.
 * @property-read SchemaTypeList<ItemAvailability>                                                $availability              The availability of this item—for example In stock, Out of stock, Pre-order, etc.
 * @property-read SchemaTypeList<BusinessEntityType>                                              $eligibleCustomerType      The type(s) of customers for which the given offer is valid.
 * @property-read SchemaTypeList<URL|Text>                                                        $asin                      An Amazon Standard Identification Number (ASIN) is a 10-character alphanumeric unique identifier assigned by Amazon.com and its partners for product identification within the Amazon organization (summary from [Wikipedia](https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number)'s article).
 * @property-read SchemaTypeList<QuantitativeValue|Duration>                                      $leaseLength               Length of the lease for some [[Accommodation]], either particular to some [[Offer]] or in some cases intrinsic to the property.
 * @property-read SchemaTypeList<Offer>                                                           $addOn                     An additional offer that can only be obtained in combination with the first base offer (e.g. supplements and extensions that are available for a surcharge).
 * @property-read SchemaTypeList<QuantitativeValue>                                               $inventoryLevel            The current approximate inventory level for the item or items.
 */
interface Offer extends Intangible
{
}
