<?php

declare(strict_types=1);

namespace Brick\Schema\Interfaces;

use Brick\Schema\SchemaTypeList;
use Brick\Schema\DataType\Text;

/**
 * schema:Service
 *
 * @property-read SchemaTypeList<OfferCatalog>                                         $hasOfferCatalog  Indicates an OfferCatalog listing for this Organization, Person, or Service.
 * @property-read SchemaTypeList<Product|Service>                                      $isRelatedTo      A pointer to another, somehow related product (or multiple products).
 * @property-read SchemaTypeList<Product|Service>                                      $isSimilarTo      A pointer to another, functionally similar product (or multiple products).
 * @property-read SchemaTypeList<Text>                                                 $slogan           A slogan or motto associated with the item.
 * @property-read SchemaTypeList<Text>                                                 $award            An award won by or for this item.
 * @property-read SchemaTypeList<Review>                                               $review           A review of the item.
 * @property-read SchemaTypeList<Text|URL>                                             $termsOfService   Human-readable terms of service documentation.
 * @property-read SchemaTypeList<Organization|Brand>                                   $brand            The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
 * @property-read SchemaTypeList<Person|Organization>                                  $broker           An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.
 * @property-read SchemaTypeList<URL|ImageObject>                                      $logo             An associated logo.
 * @property-read SchemaTypeList<Text>                                                 $providerMobility Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
 * @property-read SchemaTypeList<Text|Place|AdministrativeArea|GeoShape>               $areaServed       The geographic area where a service or offered item is provided.
 * @property-read SchemaTypeList<Demand|Offer>                                         $offers           An offer to provide this item—for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
 * @property-read SchemaTypeList<AdministrativeArea|GeoShape|Place>                    $serviceArea      The geographic area where the service is provided.
 * @property-read SchemaTypeList<Audience>                                             $audience         An intended audience, i.e. a group for whom something was created.
 * @property-read SchemaTypeList<ServiceChannel>                                       $availableChannel A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
 * @property-read SchemaTypeList<Text|URL|CategoryCode|PhysicalActivityCategory|Thing> $category         A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
 * @property-read SchemaTypeList<OpeningHoursSpecification>                            $hoursAvailable   The hours during which this service or contact is available.
 * @property-read SchemaTypeList<AggregateRating>                                      $aggregateRating  The overall rating, based on a collection of reviews or ratings, of the item.
 * @property-read SchemaTypeList<Audience>                                             $serviceAudience  The audience eligible for this service.
 * @property-read SchemaTypeList<Thing>                                                $serviceOutput    The tangible thing generated by the service, e.g. a passport, permit, etc.
 * @property-read SchemaTypeList<Person|Organization>                                  $provider         The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
 * @property-read SchemaTypeList<Thing>                                                $produces         The tangible thing generated by the service, e.g. a passport, permit, etc.
 * @property-read SchemaTypeList<GovernmentBenefitsType|Text>                          $serviceType      The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
 * @property-read SchemaTypeList<Certification>                                        $hasCertification Certification information about a product, organization, service, place, or person.
 */
interface Service extends Intangible
{
}
