name: CI

on:
    push:
        branches: [master]
    pull_request:

env:
    PSALM_PHP_VERSION: "8.4"

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PSALM_PHP_VERSION }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3

            - name: Run Psalm
              run: vendor/bin/psalm --no-progress
